name: wisekids_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0
  shimmer: ^1.0.1
  slide_popup_dialog:
    path: ./slide_popup_dialog-0.0.2/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icon/music-and-multimedia.svg
    - assets/images/187x215_boi_character.png
    - assets/images/187x215_Cat_character.png
    - assets/images/187x215_girl_character.png
    - assets/icon/Button_Or.svg
    - assets/icon/back_button_OR_cir.svg
    - assets/icon/bgPattern.png
    - assets/images/kidsInfoBoy.png
    - assets/images/kidsInfoCat.png
    - assets/images/kidsInfoGirl.png
    - assets/images/speechBubble.svg
    - assets/images/whiteCloudBG.svg
    - assets/images/avatar_boy.png
    - assets/images/avatar_girl.png
    - assets/images/avatar_cat.png
    - assets/icon/Category.svg
    - assets/icon/Vocabuary.svg
    - assets/icon/arrowDown.svg
    - assets/images/Book1.png
    - assets/images/Book2.png
    - assets/images/Book3.png
    - assets/images/Book4.png
    - assets/images/Book5.png
    - assets/images/Book6.png
    - assets/images/Book7.png
    - assets/images/Book8.png
    - assets/images/bgPattern.svg
    - assets/icon/Button_Bl.svg
    - assets/icon/Button_Pp.svg
    - assets/icon/Button_Yl.svg
    - assets/animation/Firework.flr
    - assets/icon/iconClose.svg
    - assets/icon/selectYourTheme.svg
    - assets/icon/IconChecked.svg
    - assets/icon/arrowRight.svg
    - assets/icon/wiseKidsLogoLogin.svg
    - assets/icon/Sign_in_to_set_up_multiple_profiles.svg
    - assets/icon/Facebook.svg
    - assets/icon/Google.svg
    - assets/images/loginPropBoyGirl.png
    - assets/images/loginPropCat.png
    - assets/icon/vocabuaryPopup.svg
    - assets/icon/bookshelf.svg
    - assets/icon/readAgain.svg
    - assets/icon/favourite.svg
    - assets/icon/new.svg
    - assets/icon/treasure-map.svg
    - assets/icon/learning.svg
    - assets/icon/animal.svg
    - assets/icon/holiday.svg
    - assets/icon/sport.svg
    - assets/icon/science.svg

  fonts:
    - family: NunitoRegular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: NunitoBlack
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: NunitoBlackItalic
      fonts:
        - asset: assets/fonts/Nunito-BlackItalic.ttf
    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: NunitoBoldItalic
      fonts:
        - asset: assets/fonts/Nunito-BoldItalic.ttf
    - family: NunitoExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
    - family: NunitoExtraBoldItalic
      fonts:
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
    - family: NunitoExtraLight
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: NunitoExtraLightItalic
      fonts:
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
    - family: NunitoItalic
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
    - family: NunitoLight
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: NunitoLightItalic
      fonts:
        - asset: assets/fonts/Nunito-LightItalic.ttf
    - family: NunitoSemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: NunitoSemiBoldItalic
      fonts:
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
